name: CI/CD: Deploy Infrastructure and Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Deploy Infrastructure using Bicep
      - name: Deploy Infrastructure
        run: |
          az deployment group create \
            --resource-group <your-resource-group> \
            --template-file infrastructure/main.bicep \
            --parameters infrastructure/parameters.json

      # Step 4: Set up .NET environment
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Step 5: Restore dependencies
      - name: Restore Dependencies
        working-directory: src
        run: dotnet restore

      # Step 6: Build the application
      - name: Build Application
        working-directory: src
        run: dotnet build --configuration Release --no-restore

      # Step 7: Publish the application
      - name: Publish Application
        working-directory: src
        run: dotnet publish --configuration Release --output ./publish

      # Step 8: Deploy application to Azure Web App
      - name: Deploy Application
        uses: azure/webapps-deploy@v2
        with:
          app-name: your-webapp-name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: src/publish
