---
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Infrastructure
        run: |
          az deployment group create \
            --resource-group <your-resource-group> \
            --template-file infrastructure/main.bicep \
            --parameters infrastructure/parameters.json
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore Dependencies
        working-directory: src
        run: dotnet restore
      - name: Build Application
        working-directory: src
        run: dotnet build --configuration Release --no-restore
      - name: Publish Application
        working-directory: src
        run: dotnet publish --configuration Release --output ./publish
      - name: Deploy Application
        uses: azure/webapps-deploy@v2
        with:
          app-name: your-webapp-name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: src/publish
